### ISSUE TITLE
Error while saving diffusion model in stable diffusion

### ISSUE THREAD

**Issue by deep-diver** [keras-team/keras-cv#1131]
cc @sayakpaul 

I am trying to save each part of Stable Diffusion with the code snippet below
```python
import keras_cv
from tensorflow.experimental import tensorrt

from keras_cv.models.generative.stable_diffusion.stable_diffusion import TextEncoder
from keras_cv.models.generative.stable_diffusion.stable_diffusion import DiffusionModel
from keras_cv.models.generative.stable_diffusion.stable_diffusion import Decoder

MAX_PROMPT_LENGTH = 77

IMG_HEIGHT = 512
IMG_WIDTH = 512

encoder = TextEncoder(MAX_PROMPT_LENGTH)
stable_diffusion = DiffusionModel(IMG_HEIGHT, IMG_WIDTH, MAX_PROMPT_LENGTH)
decoder = Decoder(IMG_HEIGHT, IMG_WIDTH)

encoder.save('encoder')
stable_diffusion.save('stable_diffusion')
decoder.save('decoder')
```

However, when I run the code snippet, I get the following error in the line of `stable_diffusion.save('stable_diffusion')`.

```
Traceback (most recent call last):
  File "tf_trt_conversion_sd.py", line 18, in <module>
    stable_diffusion.save('stable_diffusion')
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
TypeError: Exception encountered when calling layer "group_normalization_60" "                 f"(type GroupNormalization).

len is not well defined for a symbolic Tensor (Shape:0). Please call `x.shape` rather than `len(x)` for shape information.

Call arguments received by layer "group_normalization_60" "                 f"(type GroupNormalization):
  • args=('tf.Tensor(shape=(None, 64, 64, 320), dtype=float32)',)
  • kwargs=<class 'inspect._empty'>
```

I am using the following versions of packages:
- Python: 3.8.10
- TensorFlow: 2.10.0
- Keras-CV: 0.3.4

What would be the reason for this error? If I did something wrong, please correct me

**Comment by bhack** [comment]
See https://github.com/keras-team/keras-cv/pull/1035

Can you try with Keras-CV: 0.3.5?

**Comment by deep-diver** [comment]
Thanks for the very quick reply @bhack. `0.3.5` resolves this issue indeed!
