### ISSUE TITLE
Getting issue while importing keras_cv

### ISSUE THREAD

**Issue by SammyCoder2023** [keras-team/keras-cv#1678]
Versions : Python 3.11.2, tensor Flow 2.12.0

Error Trace
"You do not have Waymo Open Dataset installed, so KerasCV Waymo metrics are not available.
Traceback (most recent call last):
  File "C:\Users\ADMIN\Desktop\Project\DiscordServer\testSD.py", line 2, in <module>
    import keras_cv
  File "C:\Python311\Lib\site-packages\keras_cv\__init__.py", line 22, in <module>
    from keras_cv import datasets
  File "C:\Python311\Lib\site-packages\keras_cv\datasets\__init__.py", line 14, in <module>
    from keras_cv.datasets import pascal_voc
  File "C:\Python311\Lib\site-packages\keras_cv\datasets\pascal_voc\__init__.py", line 14, in <module>
    from keras_cv.datasets.pascal_voc.load import load
  File "C:\Python311\Lib\site-packages\keras_cv\datasets\pascal_voc\load.py", line 16, in <module>
    import tensorflow_datasets as tfds
  File "C:\Python311\Lib\site-packages\tensorflow_datasets\__init__.py", line 43, in <module>
    import tensorflow_datasets.core.logging as _tfds_logging
  File "C:\Python311\Lib\site-packages\tensorflow_datasets\core\__init__.py", line 22, in <module>
    from tensorflow_datasets.core import community
  File "C:\Python311\Lib\site-packages\tensorflow_datasets\core\community\__init__.py", line 18, in <module>
    from tensorflow_datasets.core.community.huggingface_wrapper import mock_builtin_to_use_gfile
  File "C:\Python311\Lib\site-packages\tensorflow_datasets\core\community\huggingface_wrapper.py", line 31, in <module>
    from tensorflow_datasets.core import dataset_builder
  File "C:\Python311\Lib\site-packages\tensorflow_datasets\core\dataset_builder.py", line 34, in <module>
    from tensorflow_datasets.core import dataset_info
  File "C:\Python311\Lib\site-packages\tensorflow_datasets\core\dataset_info.py", line 47, in <module>
    from tensorflow_datasets.core import file_adapters
  File "C:\Python311\Lib\site-packages\tensorflow_datasets\core\file_adapters.py", line 29, in <module>
    from array_record.python import array_record_module
ImportError: cannot import name 'array_record_module' from 'array_record.python' (C:\Python311\Lib\site-packages\array_record\python\__init__.py)

**Comment by ID6109** [comment]
Try referring to [this](https://github.com/keras-team/keras-cv/blob/a402f614c48924ebcfddbec6a57a18dbfc21f1ab/keras_cv/datasets/waymo/README.md#the-waymo-open-dataset-in-keras_cv).

**Comment by LukeWood** [comment]
Closing as it has been 3~ weeks and we don't have a consensus on the offending code!

If you are receiving these issues when installing from:
```
pip install git+https://github.com/keras-team/keras-cv
```
then feel free to re-open!
