### ISSUE TITLE
[Error] Using `AugMix` or `RandomShear` results in Tracebacks for missing functions

### ISSUE THREAD

**Issue by suvadityamuk** [keras-team/keras-cv#1835]
I think that there is an issue with the `keras_cv.augmentation.AugMix` layer wherein `RandomShear` uses a `_format_transform` function. It seems that neither `RandomShear` nor `VectorizedBaseImageAugmentationLayer` (the base class) have such a function.

[Link to code](https://github.com/keras-team/keras-cv/blob/b514c84650bc2851826e63328a6185077d7c747b/keras_cv/layers/preprocessing/random_shear.py)

On the other hand, it seems that `_format_transform` exists in the `OldRandomShear` class

https://github.com/keras-team/keras-cv/blob/b514c84650bc2851826e63328a6185077d7c747b/benchmarks/vectorized_random_shear.py#L119-L121

which was copied from a legacy version of the function in KerasCV

https://github.com/keras-team/keras-cv/blob/cd12204b1f6df37b15359b6adf222b9ef0f67dc8/keras_cv/layers/preprocessing/random_shear.py#L27

To reproduce (standalone example):

```python

image = tf.random.normal((1, 224, 224, 3), mean=0.5, stddev=0.5)

y = keras_cv.layers.AugMix(value_range=(0, 1))(image)
```

Original traceback:

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-70-efb9ea36b0cf>](https://localhost:8080/#) in <cell line: 3>()
      1 image = tf.random.normal((1, 224, 224, 3), mean=0.5, stddev=0.5)
      2 
----> 3 y = keras_cv.layers.AugMix(value_range=(0, 1))(image)

2 frames
[/usr/local/lib/python3.10/dist-packages/keras_cv/layers/preprocessing/aug_mix.py](https://localhost:8080/#) in tf__augment_image(self, image, transformation, **kwargs)
     12                 result = ag__.converted_call(ag__.ld(tf).zeros_like, (ag__.ld(image),), None, fscope)
     13                 curr_chain = ag__.converted_call(ag__.ld(tf).constant, ([0],), dict(dtype=ag__.ld(tf).int32), fscope)
---> 14                 (image, chain_mixing_weights, curr_chain, result) = ag__.converted_call(ag__.ld(tf).while_loop, (ag__.autograph_artifact(lambda image, chain_mixing_weights, curr_chain, result: ag__.converted_call(ag__.ld(tf).less, (ag__.ld(curr_chain), ag__.ld(self).num_chains), None, fscope)), ag__.ld(self)._loop_on_width, [ag__.ld(image), ag__.ld(chain_mixing_weights), ag__.ld(curr_chain), ag__.ld(resu...
     15                 result = ag__.ld(weight_sample) * ag__.ld(image) + (1 - ag__.ld(weight_sample)) * ag__.ld(result)
     16                 try:

AttributeError: Exception encountered when calling layer 'aug_mix_5' (type AugMix).

in user code:

    File "/usr/local/lib/python3.10/dist-packages/keras_cv/layers/preprocessing/base_image_augmentation_layer.py", line 431, in _augment  *
        image = self.augment_image(
    File "/usr/local/lib/python3.10/dist-packages/keras_cv/layers/preprocessing/aug_mix.py", line 318, in augment_image  *
        image, chain_mixing_weights, curr_chain, result = tf.while_loop(
    File "/usr/local/lib/python3.10/dist-packages/keras_cv/layers/preprocessing/aug_mix.py", line 145, in _loop_on_width
        depth_level, image_aug = tf.while_loop(
    File "/usr/local/lib/python3.10/dist-packages/keras_cv/layers/preprocessing/aug_mix.py", line 136, in _loop_on_depth
        image_aug = self._apply_op(image_aug, op_index)
    File "/usr/local/lib/python3.10/dist-packages/keras_cv/layers/preprocessing/aug_mix.py", line 287, in _apply_op
        augmented = tf.cond(
    File "/usr/local/lib/python3.10/dist-packages/keras_cv/layers/preprocessing/aug_mix.py", line 289, in <lambda>
        lambda: self._shear_x(augmented),
    File "/usr/local/lib/python3.10/dist-packages/keras_cv/layers/preprocessing/aug_mix.py", line 208, in _shear_x
        transform_x = layers.RandomShear._format_transform(

    AttributeError: type object 'RandomShear' has no attribute '_format_transform'


Call arguments received by layer 'aug_mix_5' (type AugMix):
  • inputs=tf.Tensor(shape=(1, 224, 224, 3), dtype=float32)
```

Are there any repairs/fixes for the same to refactor this?

**Comment by pure-rgb** [comment]
I wonder all those [test functions](https://github.com/keras-team/keras-cv/blob/master/keras_cv/layers/preprocessing/aug_mix_test.py) are for what! Lots of bugs and confusion.

**Comment by ianstenbit** [comment]
Thanks for the report! I've opened a PR (#1846) to get this fixed (and add better test coverage)
