### ISSUE TITLE
Retinanet Input Shape

### ISSUE THREAD

**Issue by gianlucasama** [keras-team/keras-cv#1869]
Hi! I think I found an issue with the RetinaNet class.
Referring to the last part of the example at:
[Object Detection with KerasCV](https://keras.io/guides/keras_cv/object_detection_keras_cv/#data-loading) 

This example runs, but when I change the model's backbone and I change the resizing operation to output (224, 224) shaped images, like this:

```
augmenter = keras.Sequential(
    layers=[
        keras_cv.layers.RandomFlip(
            mode="horizontal", 
            bounding_box_format="xywh"
        ),
        keras_cv.layers.JitteredResize(
            target_size=(224, 224), 
            scale_factor=(0.75, 1.3), 
            bounding_box_format="xywh"
        ),
    ]
)

model = keras_cv.models.RetinaNet.from_preset(
    "resnet18",
    num_classes=len(class_mapping),
    # For more info on supported bounding box formats, visit
    # https://keras.io/api/keras_cv/bounding_box/
    bounding_box_format="xywh",
)
```
I get the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/gianlucasama/.vscode/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/gianlucasama/.vscode/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/gianlucasama/.vscode/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/gianlucasama/.vscode/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/gianlucasama/.vscode/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/gianlucasama/.vscode/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/gianlucasama/Github/Deckard/od.py", line 158, in <module>
    model.fit(
  File "/home/gianlucasama/.local/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/tmp/__autograph_generated_filec1rr6auo.py", line 15, in tf__train_function
    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
  File "/tmp/__autograph_generated_fileatd89d7s.py", line 10, in tf__call
    difference = ag__.ld(y_true) - ag__.ld(y_pred)
ValueError: in user code:

    File "/home/gianlucasama/.local/lib/python3.10/site-packages/keras/engine/training.py", line 1284, in train_function  *
        return step_function(self, iterator)
    File "/home/gianlucasama/.local/lib/python3.10/site-packages/keras_cv/losses/smooth_l1.py", line 38, in call  *
        difference = y_true - y_pred

    ValueError: Dimensions must be equal, but are 9351 and 9441 for '{{node SmoothL1Loss/sub}} = Sub[T=DT_FLOAT](retina_net_label_encoder/strided_slice_23, retina_net/box/concat)' with input shapes: [1,9351,4], [1,9441,4].
```
Am I missing something? Shouldn't the "resnet18" backbone have a (224, 224) input shape? I also tried with other backbones and the only input shape that seems to work is (640, 640).

**Comment by GabrielGarcia1995** [comment]
I am having the same problem. It happens with any backbone. The only input shape that works is (640, 640).
Is there any way to use other input shape?

**Comment by ianstenbit** [comment]
I'm taking a look at this now -- it looks like there's a mismatch between the number of anchors in the predictions vs the encoded labels.

**Comment by ianstenbit** [comment]
It looks like the issue is due to a bug in the RetinaNet AnchorGenerator. Basically if an image isn't a multiple of 128 in width and height, the AnchorGenerator doesn't seem to prune out-of-bound boxes correctly.

As a workaround, if you use an input size that is a multiple of 128, this should work fine (I've tested this with the example on KerasIO that you referenced @gianlucasama.

If either you or @GabrielGarcia1995 have issues with that workaround, let me know. I am seeing if it's straightforward to fix the AnchorGenerator.
