### ISSUE TITLE
Error Loading Saved Object Detection Model: Found 2 Python Objects that were not bound to a checkpointed value.

### ISSUE THREAD

**Issue by shreypareek1991** [keras-team/keras-cv#1965]
I am getting this error while trying to load a saved object detection model. 

```shell 
WARNING:tensorflow:Looks like there is an object (perhaps variable or layer) that is shared between different layers/models. This may cause issues when restoring the variable values. Object: <keras_cv.models.object_detection.retinanet.prediction_head.PredictionHead object at 0x17703d510>
WARNING:tensorflow:Looks like there is an object (perhaps variable or layer) that is shared between different layers/models. This may cause issues when restoring the variable values. Object: <keras.src.layers.reshaping.reshape.Reshape object at 0x2cc6a0640>
WARNING:tensorflow:Looks like there is an object (perhaps variable or layer) that is shared between different layers/models. This may cause issues when restoring the variable values. Object: <keras_cv.models.object_detection.retinanet.retinanet_label_encoder.RetinaNetLabelEncoder object at 0x17703c3d0>
Traceback (most recent call last):
  File "/Users/shreypareek/Desktop/Projects/dev/carve/science/src/main.py", line 234, in <module>
    main()
  File "/Users/shreypareek/Desktop/Projects/dev/carve/science/src/main.py", line 205, in main
    detector = Detector(
  File "/Users/shreypareek/Desktop/Projects/dev/carve/science/src/tools/object_detection/detector.py", line 38, in __init__
    loaded_model = tf.keras.models.load_model(model_path)
  File "/Users/shreypareek/mambaforge/envs/cv_pipeline/lib/python3.10/site-packages/keras/src/saving/saving_api.py", line 238, in load_model
    return legacy_sm_saving_lib.load_model(
  File "/Users/shreypareek/mambaforge/envs/cv_pipeline/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/shreypareek/mambaforge/envs/cv_pipeline/lib/python3.10/site-packages/tensorflow/python/checkpoint/checkpoint.py", line 867, in assert_existing_objects_matched
    raise AssertionError(
AssertionError: Found 2 Python objects that were not bound to checkpointed values, likely due to changes in the Python program. Showing 2 of 2 unmatched objects: [<tf.Variable 'total:0' shape=() dtype=float32, numpy=0.0>, <tf.Variable 'count:0' shape=() dtype=float32, numpy=0.0>]
(
```

Script used for saving model
```python
model.build([1, input_image_size[0], input_image_size[1], channels])
model.save(model_save_path, include_optimizer=None, save_traces=None)
```

Contents of the saved model 
``` shell
assets                  fingerprint.pb          keras_metadata.pb       saved_model.pb          variables
```

**Comment by jbischof** [comment]
Hi @shreypareek1991 can you provide a minimal colab gist to reproduce the issue?

**Comment by shreypareek1991** [comment]
@jbischof 
I figured out the issue. The colab gist might not recreate the error.

The original model was trained using `keras-cv v0.5.x`. The error occurs when trying to load it with `v0.6.x`
It works fine if I
```shell
pip uninstall keras-cv -y
pip install keras-cv==0.5.1
```
