### ISSUE TITLE
'size' must be a 1-D int32 Tensor Call arguments received by layer 'resizing' (type Resizing): inputs=tf.Tensor(shape=(None, 1, 1, 256), dtype=float16)

### ISSUE THREAD

**Issue by innat** [keras-team/keras-cv#2005]
tried to run deeplab getting errors.

- model: deplabv3-plus
- mixed precision: True or False

Error raised from [here](https://github.com/keras-team/keras-cv/blob/45292eb340b8159d56eddbb8aea1b81db2d9473f/keras_cv/layers/spatial_pyramid.py#L159C22-L161).

```python
!pip install -q -U git+https://github.com/keras-team/keras-cv.git
!pip install -q -U keras-core


mport keras_cv
from keras_cv.models import ResNet50Backbone, DeepLabV3Plus

keras.mixed_precision.set_global_policy("mixed_float16")

backbone = ResNet50Backbone.from_preset(
        "resnet50_imagenet", include_rescaling=False
    )
model = DeepLabV3Plus(
  num_classes=n_classes, 
  backbone=backbone,
  input_shape=(IMAGE_SIZE, IMAGE_SIZE, 3),
  segmentation_head_activation=activation
)
```
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[21], line 5
      1 with strategy.scope():
      2     backbone = ResNet50Backbone.from_preset(
      3         "resnet50_imagenet", include_rescaling=False
      4     )
----> 5     model = DeepLabV3Plus(
      6         num_classes=n_classes, 
      7         backbone=backbone,
      8 #         input_shape=(IMAGE_SIZE, IMAGE_SIZE, 3),
      9         segmentation_head_activation=activation
     10     )
     11     optim, loss_fn, metrics = compile_fn()
     12     model.compile(
     13         optimizer=optim, loss=loss_fn, metrics=metrics
     14     )

File /opt/conda/lib/python3.10/site-packages/keras_cv/models/segmentation/deeplab_v3_plus/deeplab_v3_plus.py:125, in DeepLabV3Plus.__init__(self, backbone, num_classes, projection_filters, spatial_pyramid_pooling, segmentation_head, **kwargs)
    121 if spatial_pyramid_pooling is None:
    122     spatial_pyramid_pooling = SpatialPyramidPooling(
    123         dilation_rates=[6, 12, 18]
    124     )
--> 125 spp_outputs = spatial_pyramid_pooling(backbone_features["P5"])
    127 low_level_feature_projector = keras.Sequential(
    128     [
    129         keras.layers.Conv2D(
   (...)
    138     ]
    139 )
    141 low_level_projected_features = low_level_feature_projector(
    142     backbone_features["P2"]
    143 )

File /opt/conda/lib/python3.10/site-packages/keras/utils/traceback_utils.py:70, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     67     filtered_tb = _process_traceback_frames(e.__traceback__)
     68     # To get the full stack trace, call:
     69     # `tf.debugging.disable_traceback_filtering()`
---> 70     raise e.with_traceback(filtered_tb) from None
     71 finally:
     72     del filtered_tb

File /tmp/__autograph_generated_filermccmic1.py:33, in outer_factory.<locals>.inner_factory.<locals>.tf__call(self, inputs, training)
     31 temp = ag__.Undefined('temp')
     32 ag__.for_stmt(ag__.ld(self).aspp_parallel_channels, None, loop_body, get_state, set_state, (), {'iterate_names': 'channel'})
---> 33 ag__.ld(result)[-1] = ag__.converted_call(ag__.converted_call(ag__.ld(keras).layers.Resizing, (ag__.ld(inputs).shape[1], ag__.ld(inputs).shape[2]), dict(interpolation='bilinear'), fscope), (ag__.ld(result)[-1],), None, fscope)
     34 result = ag__.converted_call(ag__.ld(ops).concatenate, (ag__.ld(result),), dict(axis=-1), fscope)
     35 result = ag__.converted_call(ag__.ld(self).projection, (ag__.ld(result),), dict(training=ag__.ld(training)), fscope)

ValueError: Exception encountered when calling layer "spatial_pyramid_pooling_1" (type SpatialPyramidPooling).

in user code:

    File "/opt/conda/lib/python3.10/site-packages/keras_cv/layers/spatial_pyramid.py", line 159, in call  *
        result[-1] = keras.layers.Resizing(
    File "/opt/conda/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler  **
        raise e.with_traceback(filtered_tb) from None

    ValueError: Exception encountered when calling layer 'resizing' (type Resizing).
    
    'size' must be a 1-D int32 Tensor
    
    Call arguments received by layer 'resizing' (type Resizing):
      • inputs=tf.Tensor(shape=(None, 1, 1, 256), dtype=float16)


Call arguments received by layer "spatial_pyramid_pooling_1" (type SpatialPyramidPooling):
  • inputs=tf.Tensor(shape=(None, None, None, 2048), dtype=float16)
  • training=None
```

[n.b. Is mixed precision tested across segmentation, classification, detection, processing, and augmentation layers?

**Comment by ianstenbit** [comment]
Is this failing both with and without mixed precision?

A couple things to try:
- Pass an image size to your backbone when you initialize it
- Make sure all your images are resized to the same size during preprocessing

A full repro colab is helpful! I see from the stack trace that the code sample in the issue isn't the exact same code that was run previously (particularly wrt the `input_shape` specification, which btw should happen on the init of the backbone)
