### ISSUE TITLE
Error replicating RetinaNet example

### ISSUE THREAD

**Issue by silvada95** [keras-team/keras-cv#2013]
Hi, I am trying to replicate the example from https://github.com/keras-team/keras-cv/blob/master/examples/training/object_detection/pascal_voc/retinanet.py.

The following error is appearing during the validation:

Traceback (most recent call last):

  File "/home/silvada/anaconda3/envs/my_env/lib/python3.9/site-packages/keras_cv/callbacks/pycoco_callback.py", line 132, in on_epoch_end
    metrics = compute_pycoco_metrics(ground_truth, predictions)
  File "/home/silvada/anaconda3/envs/my_env3/lib/python3.9/site-packages/keras_cv/metrics/coco/pycoco_wrapper.py", line 219, in compute_pycoco_metrics
    coco_predictions = _convert_predictions_to_coco_annotations(predictions)
  File "/home/silvada/anaconda3/envs/my_env/lib/python3.9/site-packages/keras_cv/metrics/coco/pycoco_wrapper.py", line 131, in _convert_predictions_to_coco_annotations
    predictions["detection_boxes"][i][j]

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

I am using tensorflow 2.13.0 and keras-cv 0.6.1

**Comment by jbischof** [comment]
This is an old version of the guide. You can see the latest at https://keras.io/guides/keras_cv/object_detection_keras_cv/

**Comment by silvada95** [comment]
> This is an old version of the guide. You can see the latest at https://keras.io/guides/keras_cv/object_detection_keras_cv/. Another newer resource is https://keras.io/examples/vision/yolov8/

Hi, I am using this one. My detector works well, but the Box Coco Metrics is not working fine. It always gives almost zero values despite the fact of the detections being almost perfect.

**Comment by jbischof** [comment]
@silvada95 could you share a minimal colab gist replicating the issue? Unfortunately it is hard to replicate this unexpected performance.

**Comment by silvada95** [comment]
> 
Here is the code I am using. There are cases with both EvaluateCocoMetrics and PyCOCOCallbacks. If you look at the example at https://keras.io/guides/keras_cv/object_detection_keras_cv/, you will see that the author did not get any mAP after 20 epochs.

`import tensorflow as tf
import tensorflow_datasets as tfds
from tensorflow import keras
from tensorflow.keras import optimizers
import keras_cv
import numpy as np
from keras_cv import bounding_box
import os
import sys
import resource
from keras_cv import visualization
import tqdm

class_ids = [
    "Aeroplane",
    "Bicycle",
    "Bird",
    "Boat",
    "Bottle",
    "Bus",
    "Car",
    "Cat",
    "Chair",
    "Cow",
    "Dining Table",
    "Dog",
    "Horse",
    "Motorbike",
    "Person",
    "Potted Plant",
    "Sheep",
    "Sofa",
    "Train",
    "Tvmonitor",
    "Total",
]
class_mapping = dict(zip(range(len(class_ids)), class_ids))
BATCH_SIZE = 8

def visualize_dataset(inputs, value_range, rows, cols, bounding_box_format):
    # this function is not working properly
    inputs = next(iter(inputs.take(1)))
    images, bounding_boxes = inputs["images"], inputs["bounding_boxes"]
    visualization.plot_bounding_box_gallery(
        images,
        value_range=value_range,
        rows=rows,
        cols=cols,
        y_true=bounding_boxes,
        scale=5,
        font_scale=0.7,
        bounding_box_format=bounding_box_format,
        class_mapping=class_mapping,
    )

def unpackage_raw_tfds_inputs(inputs, bounding_box_format):
    image = inputs["image"]
    boxes = keras_cv.bounding_box.convert_format(
        inputs["objects"]["bbox"],
        images=image,
        source="rel_yxyx",
        target=bounding_box_format,
    )
    bounding_boxes = {
        "classes": tf.cast(inputs["objects"]["label"], dtype=tf.float32),
        "boxes": tf.cast(boxes, dtype=tf.float32),
    }
    return {"images": tf.cast(image, tf.float32), "bounding_boxes": bounding_boxes}


def load_pascal_voc(split, dataset, bounding_box_format):
    ds = tfds.load(dataset, split=split, with_info=False, shuffle_files=True)
    ds = ds.map(
        lambda x: unpackage_raw_tfds_inputs(x, bounding_box_format=bounding_box_format),
        num_parallel_calls=tf.data.AUTOTUNE,
    )
    return ds


train_ds = load_pascal_voc(
    split="train", dataset="voc/2007", bounding_box_format="xywh"
)
eval_ds = load_pascal_voc(split="test", dataset="voc/2007", bounding_box_format="xywh")

train_ds = train_ds.shuffle(BATCH_SIZE * 4)

train_ds = train_ds.ragged_batch(BATCH_SIZE, drop_remainder=True)
eval_ds = eval_ds.ragged_batch(BATCH_SIZE, drop_remainder=True)



augmenter = keras.Sequential(
    layers=[
        keras_cv.layers.RandomFlip(mode="horizontal", bounding_box_format="xywh"),
        keras_cv.layers.JitteredResize(
            target_size=(640,640), scale_factor=(0.75, 1.3), bounding_box_format="xywh"
        ),
    ]
)

train_ds = train_ds.map(augmenter, num_parallel_calls=tf.data.AUTOTUNE)

inference_resizing = keras_cv.layers.Resizing(
    640, 640, bounding_box_format="xywh", pad_to_aspect_ratio=True
)
eval_ds = eval_ds.map(inference_resizing, num_parallel_calls=tf.data.AUTOTUNE)


def dict_to_tuple(inputs):
    return inputs["images"], inputs["bounding_boxes"]


train_ds = train_ds.map(dict_to_tuple, num_parallel_calls=tf.data.AUTOTUNE)
eval_ds = eval_ds.map(dict_to_tuple, num_parallel_calls=tf.data.AUTOTUNE)

train_ds = train_ds.prefetch(tf.data.AUTOTUNE)
eval_ds = eval_ds.prefetch(tf.data.AUTOTUNE)

########################## OPTIMIZER ##########################################

base_lr = 0.005
# including a global_clipnorm is extremely important in object detection tasks
optimizer = tf.keras.optimizers.SGD(
    learning_rate=base_lr, momentum=0.9, global_clipnorm=10.0, weight_decay = 0.0005, use_ema = True
)

####### defining a model ###################################################

backbone = keras_cv.models.YOLOV8Backbone.from_preset(
    "yolo_v8_xs_backbone"
)

model = keras_cv.models.YOLOV8Detector(
    backbone = backbone,
    num_classes = len(class_mapping),
    bounding_box_format ="xywh",
    fpn_depth=2
)


print(model.summary())
########################## LOSS FUNCTION ###################################

model.compile(
    classification_loss='binary_crossentropy',
    box_loss='ciou',
    optimizer=tf.optimizers.SGD(global_clipnorm=10.0),
    jit_compile=False,
)

######################## metrics ###########################################


class EvaluateCOCOMetricsCallback(keras.callbacks.Callback):
    def __init__(self, data):
        super().__init__()
        self.data = data
        self.metrics = keras_cv.metrics.BoxCOCOMetrics(
            bounding_box_format="xywh",
            # passing 1e9 ensures we never evaluate until
            # `metrics.result(force=True)` is
            # called.
            evaluate_freq=1,
        )

    def on_epoch_end(self, epoch, logs):
        self.metrics.reset_state()
        for batch in tqdm.tqdm(self.data):
            images, y_true = batch[0], batch[1]
            y_pred = self.model.predict(images, verbose=0)
            self.metrics.update_state(y_true, y_pred)

        metrics = self.metrics.result(force=True)
        logs.update(metrics)
        return logs


################## training ###################################
#with tf.device('/GPU:0'):
# model.fit(
#    train_ds,#.take(20),
#    validation_data=eval_ds,#.take(20),
#    # Run for 10-35~ epochs to achieve good scores.
#    epochs=100,
#    callbacks=[keras_cv.callbacks.PyCOCOCallback(eval_ds, bounding_box_format="xywh")],
#)


with tf.device('/GPU:0'):
 model.fit(
    train_ds,#.take(20),
    validation_data=eval_ds,#.take(20),
    # Run for 10-35~ epochs to achieve good scores.
    epochs=100,
    callbacks=[EvaluateCOCOMetricsCallback(eval_ds)],
)`

**Comment by silvada95** [comment]
Here is the code I am using. If you look at the example at https://keras.io/guides/keras_cv/object_detection_keras_cv/, you will see that the author did not get any mAP after 20 epochs.

https://colab.research.google.com/drive/1vD7p8qjAX8sXpKuFZpkZl9619yMGqYTE?usp=sharing

**Comment by jbischof** [comment]
@silvada95 I do not see any output saved in that notebook.

**Comment by silvada95** [comment]
> @silvada95 I do not see any output saved in that notebook.

Hi, I did not run it on Colab because it would take too much time.

However, I attached some prints of the same code running on my local Ubuntu machine.

**Comment by sachinprasadhs** [comment]
Thanks for reporting the issue.

`RetinaNet` with the new implementation is now part of [KerasHub](https://github.com/keras-team/keras-hub) a consolidated `KerasNLP` and `KerasCV` package.
The model weights are available in `Kaggle`, for details and usage refer https://www.kaggle.com/models/keras/retinanet

We will not be making any changes to the models in `KerasCV` which are made available in `KerasHub` or the APIs/Utils made available in `Keras`.
If you still face any issue, please file a new issue in [keras-hub](https://github.com/keras-team/keras-hub)
