### ISSUE TITLE
keras_cv 0.6.3 fails on import due to conflicting "load" functions

### ISSUE THREAD

**Issue by Jack-Baumgartel** [keras-team/keras-cv#2070]
### Current Behavior:
After fresh install of keras_cv and tensorflow, keras_cv fails to import in Python 3.11 on Mac OS. (High Sierra 10.13.6)

### Expected Behavior:
Expected a successful importing of keras_cv module.

### Steps To Reproduce:
Create a new conda environment `conda create --name test python=3.11`
Activate the environment `conda activate test`
Install tensorflow  dependencies `conda install -c apple tensorflow`
Install keras_cv `pip install keras-cv tensorflow --upgrade`
Enter python `python`
Attempt to import keras_cv `import keras_cv`
See error:
```
Using TensorFlow backend
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//miniconda3/envs/test/lib/python3.11/site-packages/keras_cv/__init__.py", line 11, in <module>
    from keras_cv import datasets
  File "//miniconda3/envs/test/lib/python3.11/site-packages/keras_cv/datasets/__init__.py", line 8, in <module>
    from keras_cv.datasets import imagenet
  File "//miniconda3/envs/test/lib/python3.11/site-packages/keras_cv/datasets/imagenet/__init__.py", line 8, in <module>
    from keras_cv.src.datasets.imagenet.load import load
  File "//miniconda3/envs/test/lib/python3.11/site-packages/keras_cv/src/datasets/imagenet/__init__.py", line 14, in <module>
    from keras_cv.src.datasets.imagenet.load import load
  File "//miniconda3/envs/test/lib/python3.11/site-packages/keras_cv/src/datasets/imagenet/load.py", line 59, in <module>
    @keras_cv_export("keras_cv.datasets.imagenet.load")
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "//miniconda3/envs/test/lib/python3.11/site-packages/keras_cv/src/api_export.py", line 38, in __call__
    maybe_register_serializable(symbol, self.package)
  File "//miniconda3/envs/test/lib/python3.11/site-packages/keras_cv/src/api_export.py", line 27, in maybe_register_serializable
    keras.saving.register_keras_serializable(package=package)(symbol)
  File "//miniconda3/envs/test/lib/python3.11/site-packages/keras/saving/object_registration.py", line 154, in decorator
    raise ValueError(
ValueError: keras_cv>load has already been registered to <function load at 0x1471296c0>
```
### Version:
Pip 23.2.1
Tensorflow 2.12.0
Keras-cv 0.6.3

Any help is appreciated.

**Comment by BjarneHerland** [comment]
Looks like a variant of https://github.com/keras-team/keras-cv/issues/1998 which was fixed by https://github.com/keras-team/keras-cv/pull/2001/commits

Works (for me) when downgrading to 0.6.1, i.e.

`pip install keras_cv==0.6.1`

**Comment by Jack-Baumgartel** [comment]
Thank you @BjarneHerland, that fixed it!
