### ISSUE TITLE
Keras_cv doesn't import on Jetson

### ISSUE THREAD

**Issue by Dapid** [keras-team/keras-cv#2198]
### Current Behavior:
Importing Keras_cv on a Jetson developer kit fails to import:

```
>>> import keras_cv
Using TensorFlow backend
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/david/.virtualenvs/tf/lib/python3.8/site-packages/keras_cv/__init__.py", line 11, in <module>
    from keras_cv import datasets
  File "/home/david/.virtualenvs/tf/lib/python3.8/site-packages/keras_cv/datasets/__init__.py", line 8, in <module>
    from keras_cv.datasets import imagenet
  File "/home/david/.virtualenvs/tf/lib/python3.8/site-packages/keras_cv/datasets/imagenet/__init__.py", line 8, in <module>
    from keras_cv.src.datasets.imagenet.load import load
  File "/home/david/.virtualenvs/tf/lib/python3.8/site-packages/keras_cv/src/datasets/imagenet/__init__.py", line 14, in <module>
    from keras_cv.src.datasets.imagenet.load import load
  File "/home/david/.virtualenvs/tf/lib/python3.8/site-packages/keras_cv/src/datasets/imagenet/load.py", line 60, in <module>
    def load(
  File "/home/david/.virtualenvs/tf/lib/python3.8/site-packages/keras_cv/src/api_export.py", line 38, in __call__
    maybe_register_serializable(symbol, self.package)
  File "/home/david/.virtualenvs/tf/lib/python3.8/site-packages/keras_cv/src/api_export.py", line 27, in maybe_register_serializable
    keras.saving.register_keras_serializable(package=package)(symbol)
  File "/home/david/.virtualenvs/tf/lib/python3.8/site-packages/keras/saving/object_registration.py", line 154, in decorator
    raise ValueError(
ValueError: keras_cv>load has already been registered to <function load at 0xfffef8601dc0>
```

### Expected Behavior:
I would expect the import to work.

### Version:
Python 3.8.10.
Jetpak 5.1.2
Tensorflow 2.12.0+nv23.6
Keras CV: 0.6.4 and 0.7.1 (although the latter requires Python 3.9, the former should work).
Board: Jetson Orin Nano developer kit.

**Comment by divyashreepathihalli** [comment]
@Dapid can you upgrade the TF version to 2.15 and try it?  I see this error pop up with multiple TF versions installed or with wrong version of TF.
