### ISSUE TITLE
RetinaNet train script failed

### ISSUE THREAD

**Issue by tanzhenyu** [keras-team/keras-cv#918]
Running `python examples/models/object_detection/retina_net/basic/pascal_voc/train.py`
fails at:
```
Traceback (most recent call last):
  File "/home/overflow/code/keras-cv/examples/models/object_detection/retina_net/basic/pascal_voc/train.py", line 98, in <module>
    visualize_dataset(dataset, bounding_box_format="xywh")
  File "/home/overflow/code/keras-cv/examples/models/object_detection/retina_net/basic/pascal_voc/train.py", line 87, in visualize_dataset
    boxes = keras_cv.bounding_box.convert_format(
  File "/home/overflow/code/keras-cv/keras_cv/bounding_box/converters.py", line 384, in convert_format
    result = from_xyxy_fn(in_xyxy, images=images, image_shape=image_shape)
  File "/home/overflow/code/keras-cv/keras_cv/bounding_box/converters.py", line 251, in _xyxy_to_rel_yxyx
    left, right = left / image_width, right / image_width
  File "/home/overflow/anaconda3/envs/tf29/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/overflow/anaconda3/envs/tf29/lib/python3.9/site-packages/tensorflow/python/ops/check_ops.py", line 407, in _binary_assert
    raise errors.InvalidArgumentError(
tensorflow.python.framework.errors_impl.InvalidArgumentError: Condition x == y did not hold.
Indices of first 3 different values:
[[1]
 [2]
 [3]]
Corresponding x values:
[ 9 18 27]
Corresponding y values:
[4 6 7]
First 3 elements of x:
[ 0  9 18]
First 3 elements of y:
[0 4 6]

```

Commenting out `visualize_dataset`, the script still cannot run but will raise another different error message

**Comment by bhack** [comment]
Do we have ragged tensor?

**Comment by bhack** [comment]
@tanzhenyu Confirmed you are using ragged tensors so you need to cheery-pick that PR.

But then we have another bug in visualization with ragged tensors:

```python
  File "examples/models/object_detection/retina_net/basic/pascal_voc/train.py", line 91, in visualize_dataset
    plotted_images = tf.image.draw_bounding_boxes(images, boxes[..., :4], color)
....
ValueError: TypeError: object of type 'RaggedTensor' has no len()
```

**Comment by bhack** [comment]
Other then `tf.image.draw_bounding_boxes` that doesn't support ragged images we don't support ragged tensor in other `tf.image.*` API called in:

https://github.com/keras-team/keras-cv/blob/e9390abbf12f2a906e79fb773f69fc0e76821340/examples/models/object_detection/retina_net/basic/pascal_voc/train.py#L133-L136

More in general I think we need to start to add the testabilty of the `example` folder.

**Comment by LukeWood** [comment]
Yeah this guide is quite out of date.  I’ll update it, feel free to assign to me.

**Comment by bhack** [comment]
> Yeah this guide is quite out of date. I’ll update it, feel free to assign to me.

Are we testing these example folder in the integration?
